[general]
pidfile="burrow.pid"

[logging]
filename=""
level="info"
maxsize=100
maxbackups=30
maxage=10
use-localtime=false
use-compression=true

[zookeeper]
servers=["qzkpr01.p16.eng.sjc01.qualys.com:50024"]
timeout=6
root-path="/mypath/burrow1"

[client-profile.test]
client-id="burrow-test"
kafka-version="0.11.0.1"

[cluster.local]
class-name="kafka"
servers=["qkafka04.p16.eng.sjc01.qualys.com:50360", "qkafka05.p16.eng.sjc01.qualys.com:50360", "qkafka06.p16.eng.sjc01.qualys.com:50360"]
client-profile="test"
topic-refresh=120
offset-refresh=30

[consumer.local]
class-name="kafka"
servers=["qkafka04.p16.eng.sjc01.qualys.com:50360", "qkafka05.p16.eng.sjc01.qualys.com:50360", "qkafka06.p16.eng.sjc01.qualys.com:50360"]
cluster="local"
client-profile="test"
group-blacklist="^(console-consumer-|python-kafka-consumer-|quick-).*$"
group-whitelist="burrow-test-consumer"

[httpserver.default]
address=":8000"

[storage.default]
class-name="inmemory"
workers=20
intervals=15
expire-group=604800
min-distance=1
